name: Sync API to Hugging Face Space Repo

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync server to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://user:$HF_TOKEN@huggingface.co/spaces/arpy8/hackprojects-server

          # Push only server folder to HF main branch
          git push hf `git subtree split --prefix server main`:main --force
